language: c
script: ./travis-tool.sh run_tests
before_script:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh install_github ramnathv/rCharts
- ./travis-tool.sh bootstrap
- ./travis-tool.sh install_deps
- ./travis-tool.sh github_package assertthat
notifications:
  hipchat:
    rooms:
      secure: EDP65fOlcttK52hBg/DMdUyrQG/qL/VL9ehe5SROTQPKajMe+20WEi2vAhArSXcdqWRHoP7sp3M7s8Ponq60ac11QbS5ytRP6EdIPW02M1sz0fwuUtFARBrS+9Yt1SSIghrT3zOeKlPWyhh7nmGD47B1E5xz2R+JLNAGePZyU7k=
