language: r

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libv8-dev libhdf5-7 libhdf5-dev libhdf5-serial-dev gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libgdal1h

r_binary_packages:
- maps
- rjson 
- leafletR 
- ecoengine 
- ggmap

bioc_packages: 
- sangerseqR

r_github_packages:
- jimhester/robustr
- jimhester/covr
- rstudio/leaflet
- ropensci/rgbif 
- ropensci/rinat 
- ropensci/rvertnet
- ropensci/bold 
- ropensci/taxize
- iDigBio/ridigbio

after_success:
- Rscript -e 'library(covr); coveralls()'

notifications:
  slack:
    secure: JgCatgv7Eeh6qHmi3TwWLdKHkCjnr5KHcBzVwy2F4IPafqPMEEhnSFxqP2Td8f7YcPqvdiv/blTGdgIOAi3V64O4fp3NZLLpzINNiL0i9iBZqkT71uw8ovcfrAeIHA9D9gapLtx3D4hdUF9jIyLIW2kMzIvaIA5PiDJ+oZitHow=
