language: r
cache: packages

bioc_packages:
  - sangerseqR

r_binary_packages:
  - covr
  - taxize

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings --as-cran"

matrix:
  include:
    - os: linux
      r: release
      env:
        - R_CODECOV=true
        - _R_CHECK_LENGTH_1_CONDITION_=verbose
        - _R_CHECK_LENGTH_1_LOGIC2_=verbose
    - os: linux
      r: devel
      env:
        - R_CODECOV=true
        - _R_CHECK_LENGTH_1_CONDITION_=verbose
        - _R_CHECK_LENGTH_1_LOGIC2_=verbose

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: JgCatgv7Eeh6qHmi3TwWLdKHkCjnr5KHcBzVwy2F4IPafqPMEEhnSFxqP2Td8f7YcPqvdiv/blTGdgIOAi3V64O4fp3NZLLpzINNiL0i9iBZqkT71uw8ovcfrAeIHA9D9gapLtx3D4hdUF9jIyLIW2kMzIvaIA5PiDJ+oZitHow=
