language: c
sudo: required
dist: trusty
script: ./travis-tool.sh run_tests

before_script:
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libproj-dev libproj-dev libgeos++-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh bioc_packages sangerseqR

r_check_args: "--as-cran --run-dontrun"

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: JgCatgv7Eeh6qHmi3TwWLdKHkCjnr5KHcBzVwy2F4IPafqPMEEhnSFxqP2Td8f7YcPqvdiv/blTGdgIOAi3V64O4fp3NZLLpzINNiL0i9iBZqkT71uw8ovcfrAeIHA9D9gapLtx3D4hdUF9jIyLIW2kMzIvaIA5PiDJ+oZitHow=
