language: r
cache: packages

bioc_packages:
  - sangerseqR

before_install:
  - sudo apt-get install libproj-dev libgeos++-dev

addons:
  apt:
    packages:
      - libv8-dev

after_success:
  - Rscript -e 'covr::codecov()'

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: JgCatgv7Eeh6qHmi3TwWLdKHkCjnr5KHcBzVwy2F4IPafqPMEEhnSFxqP2Td8f7YcPqvdiv/blTGdgIOAi3V64O4fp3NZLLpzINNiL0i9iBZqkT71uw8ovcfrAeIHA9D9gapLtx3D4hdUF9jIyLIW2kMzIvaIA5PiDJ+oZitHow=
